#!/usr/bin/env python3
# @file_purpose Generates the project context docs for AI agents (context.md + overviews)
# Run from the repo root: writes context.md, context_sources.md, context_tickets.md.

import os, sys
from contextlib import redirect_stdout

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                ".claude", "skills", "orientation"))
from build_context import Context

CONTEXT_MD = "context.md"
SOURCES_MD = "context_sources.md"
TICKETS_MD = "context_tickets.md"

# Folders/files to skip when listing sources.
SOURCE_EXCLUDES = [".git", ".github", ".mcp", ".claude", "__pycache__", "venv", ".venv", "tickets",
                   "output", "static", ".gitignore", ".db-wal", ".db-shm",
                   "secret_keys", "external", "build", "dist", "scratchpad",
                   ".pytest_cache", ".mypy_cache", ".ruff_cache", "egg-info",
                   "ARCHITECT_HANDOFF.md", "ARCHITECT_STATE.md",
                   CONTEXT_MD, SOURCES_MD, TICKETS_MD]


def write_entry(ctx) -> int:
    """Write the entry doc context.md. Returns non-zero on error."""
    print("# Project context")
    print("")
    print("Generated by `context.py`. Regenerate with `./context.py` from the repo root.")
    print("")
    print("--- Session info ---")
    print(f"Current Branch: {ctx.get_current_git_branch_name()}")
    print(f"Context Scope: {ctx.context_scope()}")
    print("--- Start of very important files ---")
    result = ctx.dump_important_files()
    if result != 0:
        return result
    print("--- End of very important files ---")
    print("")
    print("## Further context (read if needed)")
    print(f"- `{SOURCES_MD}` — overview of all source folders/files and their purpose.")
    print(f"- `{TICKETS_MD}` — open and done tickets.")
    return 0


def write_sources(ctx) -> None:
    print("# Source files overview")
    print("--- Folders, files and their purpose ---")
    ctx.list_files_in_directories(".", exclude_files=SOURCE_EXCLUDES)


def write_tickets(ctx) -> None:
    print("# Tickets overview")
    ctx.print_tickets()


def main(args) -> int:
    ctx = Context()
    ctx.important_files = ["README.md", "MEMORIES.md", "CONTRIBUTING.md" ]
    ctx.extensions_purpose_first_line = [".md", ".adoc"]
    ctx.ascii_printable_threshold = 0.9

    if not ctx.is_cwd_same_as_script_location():
        print("SEVERE ERROR: run ./context.py from the repo root.", file=sys.stderr)
        return 1

    with open(SOURCES_MD, "w", encoding="utf-8") as f, redirect_stdout(f):
        write_sources(ctx)
    with open(TICKETS_MD, "w", encoding="utf-8") as f, redirect_stdout(f):
        write_tickets(ctx)
    with open(CONTEXT_MD, "w", encoding="utf-8") as f, redirect_stdout(f):
        rc = write_entry(ctx)

    # Terminal-only output (never written into the context files).
    ctx.print_tmux_info()
    ctx.print_hints("--- Actions required to keep code hygiene ---")
    print(f"Wrote {CONTEXT_MD}, {SOURCES_MD}, {TICKETS_MD}")
    return rc


if __name__ == "__main__":
    exit(main(sys.argv[1:]))
