#!/bin/bash
# @file_purpose Architect self-restart: snapshot live state, clear the Architect Claude
#               session, pause, and re-bootstrap it to read the handoff + state snapshot.
#
# WHEN TO RUN: after wrapping up a work batch, when the Architect context is large and a
# fresh session is wanted. FIRST update the narrative in /home/mint/auto_placer/ARCHITECT_HANDOFF.md
# (what's in-flight, decisions, gotchas) -- this script only auto-generates the mechanical
# FACTS (git/agents/tickets) into ARCHITECT_STATE.md; it can't write the narrative.
#
# Steps (matches the intended flow):
#   1. create handoff snapshot  -> writes live state to /home/mint/auto_placer/ARCHITECT_STATE.md
#   2. clear session            -> sends /clear to the Architect tmux session
#   3. pause                    -> waits for the clear to settle
#   4. point to handoff         -> tells the fresh session to read the handoff + state
#
# Safe to run from the Architect session itself: the /clear + read keystrokes are queued
# into the Claude TUI and processed after this script's Bash call returns.

set -uo pipefail

REPO="/home/mint/auto_placer"
HANDOFF="$REPO/ARCHITECT_HANDOFF.md"
STATE="$REPO/ARCHITECT_STATE.md"
SESSION="Architect"

cd "$REPO" || { echo "cannot cd $REPO" >&2; exit 1; }

# --- Guard: warn if the narrative handoff looks stale (untouched > 6h) ---
if [ -f "$HANDOFF" ]; then
    age_min=$(( ( $(date +%s) - $(stat -c %Y "$HANDOFF") ) / 60 ))
    if [ "$age_min" -gt 360 ]; then
        echo "WARNING: $HANDOFF last updated ${age_min} min ago -- update the narrative before restarting." >&2
    fi
else
    echo "WARNING: $HANDOFF missing -- the fresh session will have only the auto state snapshot." >&2
fi

git fetch origin -q 2>/dev/null || true

# --- 1. Create the live-state snapshot (mechanical facts, overwritten each run) ---
{
    echo "# Architect live-state snapshot"
    echo ""
    echo "Auto-generated by team/Architect_restart.sh on $(date '+%Y-%m-%d %H:%M:%S')."
    echo "Read this together with the narrative in $HANDOFF."
    echo ""
    echo "- **master tip:** $(git rev-parse --short master) — $(git log -1 --format=%s master | head -c 90)"
    echo "- **origin/master:** $(git rev-parse --short origin/master 2>/dev/null || echo n/a)"
    echo ""
    echo "## Agent branches (ahead/behind master)"
    for a in coder_bob coder_john student ticketwriter; do
        if git show-ref --verify --quiet "refs/heads/$a" 2>/dev/null; then
            ahead=$(git rev-list --count "master..$a" 2>/dev/null || echo '?')
            behind=$(git rev-list --count "$a..master" 2>/dev/null || echo '?')
            echo "- $a: ${ahead} ahead / ${behind} behind"
        fi
    done
    echo ""
    echo "## Running tmux agents"
    tmux list-sessions -F '- #S' 2>/dev/null || echo "- (tmux unavailable)"
    echo ""
    echo "## Open tickets"
    ls tickets/open/*_ticket.md 2>/dev/null | sed 's#.*/##; s/_ticket.md//; s/^/- #/' || echo "- (none)"
    echo ""
    echo "## Reminders for the fresh session"
    echo "- Run \`./context.py\` (must exit 0) and read \`context.md\`."
    echo "- Confirm the suite is green: \`python -m pytest\`."
    echo "- Watchers from the previous session are gone; re-check agents with \`team/agent_status.sh <agent>\`."
    echo "- After merging an agent branch, RESET it to master (see MEMORIES) to avoid divergence."
} > "$STATE"

echo "Wrote live-state snapshot to $STATE"

# --- 2. Clear the Architect Claude session ---
echo "Clearing $SESSION session in 10s..."
sleep 10
# Send "/clear" and its submitting Enter as SEPARATE keystrokes with a pause
# between them, same reason as step 4: sending text+Enter together lets the TUI
# absorb the Enter before "/clear" settles, leaving the slash-command unsent.
tmux send-keys -t "$SESSION" "/clear"
sleep 3
tmux send-keys -t "$SESSION" Enter

# --- 3. Pause for the clear to settle ---
sleep 10

# --- 4. Point the fresh session at the handoff + state snapshot ---
# Send the message text and its submitting Enter as SEPARATE keystrokes with a
# pause between them: sending text+Enter together lets the TUI absorb the Enter
# before the pasted line settles, leaving the message unsent in the prompt.
tmux send-keys -t "$SESSION" "read $HANDOFF and $STATE — you are Architect resuming a session; then run ./context.py"
sleep 3
tmux send-keys -t "$SESSION" Enter

echo "Restart bootstrapped: cleared + pointed at handoff/state."
